# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "50edd5e2cc3630528157cdf6657100e1"
application_url = "https://geanos-store-iq-1043331012124.australia-southeast1.run.app"
embedded = true
name = "GEANOS Store IQ"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions,read_orders,read_all_orders"

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app-purchases-one-time-update"
  topics = [ "app_purchases_one_time/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]
[[webhooks.subscriptions]]
uri = "/webhooks/compliance"
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]
[auth]
redirect_urls = [ "https://geanos-store-iq-1043331012124.australia-southeast1.run.app/api/auth" ]

[build]
automatically_update_urls_on_dev = true
